<a href="https://colab.research.google.com/github/CarlosBaztan/Clases-Python-UNIR/blob/main/Clase_5_Drive_csv__preprocesado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Conectar google colab con drive

In [3]:
# Importamos la librería que permite a Colab hablar con Drive
from google.colab import drive

# Montamos nuestro disco duro virtual
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
#Leer csv
import pandas as pd
#Creamos variable donde aparece la ruta del archivo
ruta_archivo="/content/drive/MyDrive/Phyton UNIR/job_salary_prediction_dataset.csv"
df_csv=pd.read_csv(ruta_archivo)
df_csv

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [5]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

In [6]:
df_csv.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

# Preprocesado

In [ ]:
import pandas as pd

#Simulamos un dataset "sucio"
datos_sucios ={
    "ID Cliente ": [1,2,2,4,5], #Fijaos el espacio al final de ID Cliente y fijaros tambien en que el 2 está repetido
    "NombreCompleto": ["Ana", "Luis", "Luis", "Pedro", None], #Volvemos a tener Luis duplicado y no tenemos un registro
    "Edad_Años": [25,30,30,None, 45], #No tenemos la edad de Pedro
    "Columna":["X1", "X2", "X2", "X3", "X4"] #Columna que no aporta información
}
df_limpieza = pd.DataFrame(datos_sucios)
df_limpieza

   ID Cliente  NombreCompleto  Edad_Años Columna
0            1            Ana       25.0      X1
1            2           Luis       30.0      X2
2            2           Luis       30.0      X2
3            4          Pedro        NaN      X3
4            5           None       45.0      X4

Estandarizar/Renonmbrar columnas

In [ ]:
#A través del rename() pasandole un diccionario de {"nombre_viejo": "nombre_nuevo"}

df_limpieza = df_limpieza.rename(columns = {
    "ID Cliente ":"id_cliente",
    "NombreCompleto":"nombre",
    "Edad_Años": "edad",
    "Columna": "columna"
})
df_limpieza

   id_cliente nombre  edad columna
0           1    Ana  25.0      X1
1           2   Luis  30.0      X2
2           2   Luis  30.0      X2
3           4  Pedro   NaN      X3
4           5   None  45.0      X4

Eliminar lo que no aporta valor

In [ ]:
#A través de drop(). Se utiliza axis=1 para borrar una columna. Si quisieramos borrar una fila, usaríamos axis=0.
df_limpieza = df_limpieza.drop("columna", axis=1)
df_limpieza

   id_cliente nombre  edad
0           1    Ana  25.0
1           2   Luis  30.0
2           2   Luis  30.0
3           4  Pedro   NaN
4           5   None  45.0

Eliminar duplicados

In [ ]:
print(f"Filas antes de borrar duplicados: {len(df_limpieza)}")
df_limpieza=df_limpieza.drop_duplicates()
print(f"Filas despues de borrar duplicados: {len(df_limpieza)}")
df_limpieza

Filas antes de borrar duplicados: 5
Filas despues de borrar duplicados: 4

   id_cliente nombre  edad
0           1    Ana  25.0
1           2   Luis  30.0
3           4  Pedro   NaN
4           5   None  45.0

El siguiente paso es importante porque crea una copia independiente del DataFrame original en pandas, lo que permite trabajar y hacer modificaciones sobre df_limpieza_2 sin afectar a df_limpieza. Si no usaramos .copy(), ambas variables apuntarían al mismo objeto en memoria, por lo que cualquier cambio en una también modificaría la otra, pudiendo provocar errores o pérdida de datos originales durante el proceso de limpieza.

In [ ]:
df_limpieza_2=df_limpieza.copy()
df_limpieza_2

   id_cliente nombre  edad
0           1    Ana  25.0
1           2   Luis  30.0
3           4  Pedro   NaN
4           5   None  45.0

Imputar valores nulos

In [ ]:
#Imputar con un valor
df_limpieza_2["nombre"] = df_limpieza_2["nombre"].fillna("Desconocido")
df_limpieza_2

   id_cliente       nombre  edad
0           1          Ana  25.0
1           2         Luis  30.0
3           4        Pedro   NaN
4           5  Desconocido  45.0

In [ ]:
#Nivel 1: Media
media_global = df_limpieza_2["edad"].mean()
df_limpieza_2["edad"] = df_limpieza_2["edad"].fillna(media_global)
df_limpieza_2

   id_cliente       nombre       edad
0           1          Ana  25.000000
1           2         Luis  30.000000
3           4        Pedro  33.333333
4           5  Desconocido  45.000000

Volver a ejecutar la celda donde aparece:

df_limpieza_2=df_limpieza.copy()
df_limpieza_2

In [ ]:
#Nivel 1: Mediana
mediana_global = df_limpieza["edad"].median()
df_limpieza_2["edad"] = df_limpieza_2["edad"].fillna(mediana_global)
df_limpieza_2

   id_cliente nombre  edad
0           1    Ana  25.0
1           2   Luis  30.0
3           4  Pedro  30.0
4           5   None  45.0

In [ ]:
#Nivel 2. Media por grupos, se utiliza la combinación groupby() + transform()

datos_sucios = {
    'ID Cliente ': [1, 2, 2, 4, 5],
    'NombreCompleto': ['Ana', 'Luis', 'Luis', 'Pedro', None],
    'Edad_Años': [25, 25, 80, None, 45],
     "Segmento": ["VIP", "NO VIP", "VIP", "VIP", "NO VIP"],
    'Columna_Inutil_Sistema': ['X1', 'X2', 'X2', 'X3', 'X4']
}
df_limpieza = pd.DataFrame(datos_sucios)

df_limpieza = df_limpieza.rename(columns={
    'ID Cliente ': 'id_cliente',
    'NombreCompleto': 'nombre',
    'Edad_Años': 'edad',
    'Segmento': 'segmento',
    'Columna_Inutil_Sistema': 'codigo_tecnico'
})
df_limpieza = df_limpieza.drop("codigo_tecnico", axis=1)
df_limpieza["nombre"] = df_limpieza["nombre"].fillna("Desconocido")
df_limpieza

   id_cliente       nombre  edad segmento
0           1          Ana  25.0      VIP
1           2         Luis  25.0   NO VIP
2           2         Luis  80.0      VIP
3           4        Pedro   NaN      VIP
4           5  Desconocido  45.0   NO VIP

In [ ]:
# Imputar el missing de edad usando la media de cada segmento
df_limpieza["edad"] = df_limpieza["edad"].fillna(
    df_limpieza.groupby("segmento")["edad"].transform("mean")
)
df_limpieza

   id_cliente       nombre  edad segmento
0           1          Ana  25.0      VIP
1           2         Luis  25.0   NO VIP
2           2         Luis  80.0      VIP
3           4        Pedro  52.5      VIP
4           5  Desconocido  45.0   NO VIP

In [ ]:
# Nivel 3. KnnImputer
from sklearn.impute import KNNImputer

datos_clientes = {
    'id_cliente': [1, 2, 3, 4, 5],
    'nombre': ['Ana', 'Luis', 'Carlos', 'Pedro', 'Marta'],
    'ingresos_anuales': [25000, 27000, 80000, 82000, 24000], # Fijaos: Ana, Luis y Marta ganan poco. Carlos y Pedro ganan mucho.
    'gasto_mensual': [150, 180, 800, None, 140]              # Pedro es un misterio (None)
}
df_ml = pd.DataFrame(datos_clientes)
df_ml

   id_cliente  nombre  ingresos_anuales  gasto_mensual
0           1     Ana             25000          150.0
1           2    Luis             27000          180.0
2           3  Carlos             80000          800.0
3           4   Pedro             82000            NaN
4           5   Marta             24000          140.0

In [ ]:
#llamamos a la función de knn
algoritmo_knn=KNNImputer(n_neighbors=1)

#Agrupamos todas las variables numericas. porque KNN solo entiende de NUMEROS
columnas_numericas=["ingresos_anuales", "gasto_mensual"]

df_ml[["ingresos_anuales","gasto_mesual_ml"]] = algoritmo_knn.fit_transform(df_ml[columnas_numericas])
df_ml

   id_cliente  nombre  ingresos_anuales  gasto_mensual  gasto_mesual_ml
0           1     Ana           25000.0          150.0            150.0
1           2    Luis           27000.0          180.0            180.0
2           3  Carlos           80000.0          800.0            800.0
3           4   Pedro           82000.0            NaN            800.0
4           5   Marta           24000.0          140.0            140.0